const listaPalabras = [

  'delfin', 'Animal Acuático',
  'nutria', 'Animal',
  'elefante', 'Animal',
  'condor', 'Ave',
  'mercedes', 'Marca de Vehículo',
  'wolksbagen', 'Marca de Vehículo',
  'maluma','Cantante de Reggaeton',
  'java', 'Lenguaje de Programación',
  'typescript', 'Lenguaje de Programación',
  'javascript', 'Lenguaje de Programación',
  'gigabyte', 'Unidad de almacenamiento',
  'equilibrado', 'Perfectamente...',
  'laravel','Framework',
  'poker', 'Juego de cartas',
  'xiaomi', 'Marca de Celular',
  'motorola', 'Marca de Celular',
  'instrucciones', 'Guía sobre algo',
  'microfono', 'Para capturar audio',
  'star wars', 'Saga de películas',
  'Rapidos y Furiosos', 'Saga de Películas',
  'El hombre araña', 'Película',
  'Armin Van Buuren', 'DJ',
  'Brian Cross', 'DJ',
  'Cobra Kai', 'Serie',
  'La casa de papel', 'Serie',
  'Breaking Bad', 'Serie',
  'Naruto', 'Serie de dibujos',
  'The big bang teory', 'Serie'
];
